import { MantineProvider } from "@mantine/core"
import ThemeProvider from "@/app/theme-provider"
import { theme } from "@/lib/mantine-theme"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>calmi</title>
      </head>
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
