//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "notes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub author_id: i64,
    pub created_at: DateTime,
    pub to: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::note_announces::Entity")]
    NoteAnnounces,
    #[sea_orm(has_many = "super::note_likes::Entity")]
    NoteLikes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::note_announces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NoteAnnounces.def()
    }
}

impl Related<super::note_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NoteLikes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
